-- DML
/*
7. 의학과 김명훈 학생은 2005년 1학기에 자신이 수강할 '피부생리학' 점수가 잘못되었다는 것을 발견하고는 정정을 요청하였다. 
담당 교수의 확인 받은 결과 해당 과목의 학점을 3.5로 변경키로 결정되었다. 적절한 SQL 문을 작성하시오.
*/
UPDATE TB_GRADE SET POINT = 3.5
WHERE STUDENT_NO = (SELECT STUDENT_NO FROM TB_STUDENT WHERE STUDENT_NAME = '김명훈' 
AND DEPARTMENT_NO = (SELECT DEPARTMENT_NO FROM TB_DEPARTMENT WHERE DEPARTMENT_NAME = '의학과'))
AND TERM_NO = '200501'
AND CLASS_NO = (SELECT CLASS_NO FROM TB_CLASS WHERE CLASS_NAME = '피부생리학'); 

SELECT * FROM TB_GRADE 
WHERE STUDENT_NO IN (SELECT STUDENT_NO FROM TB_STUDENT WHERE STUDENT_NAME = '김명훈') AND TERM_NO = '200501'; 

SELECT CLASS_NO, CLASS_NAME FROM TB_CLASS WHERE CLASS_NO = 'C3843900'; -- 피부생리학

/* 
8. 성적 테이블(TB_GRADE) 에서 휴학생들의 성적항목을 제거하시오.
*/
SELECT * FROM TB_GRADE
JOIN TB_STUDENT USING(STUDENT_NO)
WHERE ABSENCE_YN = 'Y';

DELETE FROM TB_GRADE
WHERE STUDENT_NO IN (SELECT STUDENT_NO FROM TB_STUDENT WHERE ABSENCE_YN = 'Y');